# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Kognifai.Serialization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from Kognifai.Serialization import Basetypes_pb2 as Kognifai_dot_Serialization_dot_Basetypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cKognifai.Serialization.proto\x12\x16kognifai.serialization\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&Kognifai.Serialization.Basetypes.proto\"e\n\x0eMessageWrapper\x12\x1a\n\x12subprotocol_number\x18\x01 \x01(\r\x12 \n\x18subprotocol_message_type\x18\x02 \x01(\r\x12\x15\n\rmessage_bytes\x18\x03 \x01(\x0c\"H\n\x0cMessageArray\x12\x38\n\x08messages\x18\x01 \x03(\x0b\x32&.kognifai.serialization.MessageWrapper\"\x81\x01\n\x15MessageArrayContainer\x12\x1f\n\x17message_library_version\x18\x01 \x01(\r\x12\x16\n\x0e\x65\x64gegateway_id\x18\x02 \x01(\t\x12\x12\n\ncompressed\x18\x03 \x01(\x08\x12\x1b\n\x13message_array_bytes\x18\x04 \x01(\x0c*\xaa\x01\n\x11KnownSubprotocols\x12\x16\n\x12TimeseriesProtocol\x10\x00\x12\x11\n\rAssetProtocol\x10\x01\x12\x19\n\x15\x41larmAndEventProtocol\x10\x02\x12\x15\n\x11\x44\x61taframeProtocol\x10\x03\x12\x17\n\x13\x45\x64geGatewayProtocol\x10\x04\x12\x1f\n\x1b\x45\x64geGatewaySecurityProtocol\x10\x05\x42\x19\xaa\x02\x16Kognifai.Serializationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Kognifai.Serialization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026Kognifai.Serialization'
  _globals['_KNOWNSUBPROTOCOLS']._serialized_start=439
  _globals['_KNOWNSUBPROTOCOLS']._serialized_end=609
  _globals['_MESSAGEWRAPPER']._serialized_start=129
  _globals['_MESSAGEWRAPPER']._serialized_end=230
  _globals['_MESSAGEARRAY']._serialized_start=232
  _globals['_MESSAGEARRAY']._serialized_end=304
  _globals['_MESSAGEARRAYCONTAINER']._serialized_start=307
  _globals['_MESSAGEARRAYCONTAINER']._serialized_end=436
# @@protoc_insertion_point(module_scope)
