# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Kognifai.Serialization.Asset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from Kognifai.Serialization import Basetypes_pb2 as Kognifai_dot_Serialization_dot_Basetypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"Kognifai.Serialization.Asset.proto\x12\x16kognifai.serialization\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&Kognifai.Serialization.Basetypes.proto\"\xbf\x02\n\x06Vertex\x12\x13\n\x0b\x65xternal_id\x18\x01 \x01(\t\x12\x13\n\x0bvertex_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x32\n\x0e\x63reateded_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63hanged_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x42\n\nproperties\x18\x06 \x03(\x0b\x32..kognifai.serialization.Vertex.PropertiesEntry\x1aS\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .kognifai.serialization.Property:\x02\x38\x01\"\xf6\x01\n\x04\x45\x64ge\x12\x1a\n\x12source_external_id\x18\x01 \x01(\t\x12\x1a\n\x12target_external_id\x18\x02 \x01(\t\x12\x11\n\tedge_type\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12@\n\nproperties\x18\x05 \x03(\x0b\x32,.kognifai.serialization.Edge.PropertiesEntry\x1aS\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .kognifai.serialization.Property:\x02\x38\x01\"U\n\rSubtreeFilter\x12\x1a\n\x12levels_to_traverse\x18\x01 \x01(\r\x12\x12\n\nedge_types\x18\x02 \x03(\t\x12\x14\n\x0cvertex_types\x18\x03 \x03(\t\"\x1a\n\x18\x41ssetRootVerticesRequest\"\xa7\x01\n\x1b\x41ssetVerticesSubtreeRequest\x12\x16\n\x0esearch_root_id\x18\x01 \x01(\t\x12\x31\n\rupdated_after\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12=\n\x0esubtree_filter\x18\x03 \x01(\x0b\x32%.kognifai.serialization.SubtreeFilter\"x\n\x17\x41ssetReplicationMessage\x12\x30\n\x08vertices\x18\x01 \x03(\x0b\x32\x1e.kognifai.serialization.Vertex\x12+\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x1c.kognifai.serialization.Edge*z\n\x10\x41ssetMessageType\x12 \n\x1c\x41ssetRootVerticesRequestType\x10\x00\x12#\n\x1f\x41ssetVerticesSubtreeRequestType\x10\x01\x12\x1f\n\x1b\x41ssetReplicationMessageType\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Kognifai.Serialization.Asset_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERTEX_PROPERTIESENTRY._options = None
  _VERTEX_PROPERTIESENTRY._serialized_options = b'8\001'
  _EDGE_PROPERTIESENTRY._options = None
  _EDGE_PROPERTIESENTRY._serialized_options = b'8\001'
  _globals['_ASSETMESSAGETYPE']._serialized_start=1113
  _globals['_ASSETMESSAGETYPE']._serialized_end=1235
  _globals['_VERTEX']._serialized_start=136
  _globals['_VERTEX']._serialized_end=455
  _globals['_VERTEX_PROPERTIESENTRY']._serialized_start=372
  _globals['_VERTEX_PROPERTIESENTRY']._serialized_end=455
  _globals['_EDGE']._serialized_start=458
  _globals['_EDGE']._serialized_end=704
  _globals['_EDGE_PROPERTIESENTRY']._serialized_start=372
  _globals['_EDGE_PROPERTIESENTRY']._serialized_end=455
  _globals['_SUBTREEFILTER']._serialized_start=706
  _globals['_SUBTREEFILTER']._serialized_end=791
  _globals['_ASSETROOTVERTICESREQUEST']._serialized_start=793
  _globals['_ASSETROOTVERTICESREQUEST']._serialized_end=819
  _globals['_ASSETVERTICESSUBTREEREQUEST']._serialized_start=822
  _globals['_ASSETVERTICESSUBTREEREQUEST']._serialized_end=989
  _globals['_ASSETREPLICATIONMESSAGE']._serialized_start=991
  _globals['_ASSETREPLICATIONMESSAGE']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
