# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Kognifai.Serialization.Basetypes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&Kognifai.Serialization.Basetypes.proto\x12\x16kognifai.serialization\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n\x08Property\x12\x39\n\tdata_type\x18\x01 \x01(\x0e\x32&.kognifai.serialization.CommonDataType\x12\x14\n\x0c\x64ouble_value\x18\x02 \x01(\x01\x12\x13\n\x0bint64_value\x18\x03 \x01(\x03\x12\x14\n\x0cstring_value\x18\x04 \x01(\t\x12\x12\n\nbool_value\x18\x05 \x01(\x08*Q\n\x0e\x43ommonDataType\x12\x0e\n\nDoubleType\x10\x00\x12\x11\n\rInt64TypeType\x10\x01\x12\x0e\n\nStringType\x10\x02\x12\x0c\n\x08\x42oolType\x10\x03\x42\x19\xaa\x02\x16Kognifai.Serializationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Kognifai.Serialization.Basetypes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026Kognifai.Serialization'
  _globals['_COMMONDATATYPE']._serialized_start=256
  _globals['_COMMONDATATYPE']._serialized_end=337
  _globals['_PROPERTY']._serialized_start=100
  _globals['_PROPERTY']._serialized_end=254
# @@protoc_insertion_point(module_scope)
